### ISSUE TITLE
Hooks are applied one frame late

### ISSUE THREAD

**Issue by rparrett** [nicopap/bevy-scene-hook#8]
In Bevy 0.11, scenes are spawned in the `Update` schedule, so it's possible for `run_hooks` to run before they are spawned, so that the hooks are applied one frame late.

For me, this manifested in a shadow being visible for one frame before `NotShadowCaster` took effect.

In Bevy 0.12-dev, scenes are spawned in the `SpawnScene` schedule which runs between `Update` and `PostUpdate`.

A fix in either environment could be to schedule `run_hooks` in `PostUpdate`.  But maybe it's more proper to run in the appropriate schedule, ordered after `scene_spawner_system`.

**Comment by nicopap** [comment]
Thank you for opening the issue. I've participated to <https://github.com/bevyengine/bevy/pull/9260> as you can see. Yeah. I think running the hook in `scene_spawner_system` is going to be the solution.

**Comment by nicopap** [comment]
This should be fixed with `v9.0.0`.
